name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: phpcs src bin --standard=PSR12 
        uses: chekalsky/phpcs-action@v1
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@7.4


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
